check_punishments: Avoid re-getting member from id
Strikesy bot had a couple errors today:
- Something went wrong. Please try again, doing it a different way
this time. The problem: Command raised an exception: AttributeError:
'NoneType' object has no attribute 'add_roles'
- Something went wrong. Please try again, doing it a different way
this time. The problem: Command raised an exception: AttributeError:
'NoneType' object has no attribute 'id'

Since the error message appears after the strike message it sent, it
would mean that it happens in each individual jail function. Since
member was received, and the id was passed to search for the member
again, it's probably an error in here.